### ISSUE TITLE
Adding new variable type for Integrator API calls

### ISSUE THREAD

**Issue by fforbeck** [openlawteam/openlaw-core#135]
New Type:
```
<%
[[numberA:Number]]
[[numberB:Number]]
[[startingAt:DateTime]]

[[externalCall:ExternalCall(
serviceName: "Sum Service";
parameters: 
	numberA -> numberA,
	numberB -> numberB;
startDate: startingAt)]]
%>

[[externalCall.result.sum]]
```

With this new type we can embed calls to external services that are registered into Integrator API. 

It behaves like an ethereum call, but instead of sending a request to the ethereum network, it will send a request to our Integrator API which decides the correct external service that needs to be called with the provided arguments.

**Comment by adridadou** [comment]
What about "ExternalCall" instead of IntegratorCall? It defines a bit better what the user wants to do. (Thinking out loud, I'd love to hear your thoughts, you too @awrigh01 )

Regarding the parameters:
- the service version should be optional. If it isn't provided, the latest version should be taken and the version should be then registered in the contract.

- what is the serviceId for ? 
- argument keys don't need to be between ""
- from is not needed IMO. It's just a parameter specifically for Ethereum call. Unless you had something else in mind here. 

Let's also define what properties should this type have:
- result. The first result once the execution was successful. The type is a structure that is defined by the integrated service (ABI)
- status. The status of the call. The type is Choice("successful","pending","failed") (the first one)
- executionDate. LocalDateTime of when the execution was successful (the first one)

FUTURE_WORK: make the return type of the IntegratorCall a Collection<Result Structure> to be able to access all the results, not only the first one

**Comment by fforbeck** [comment]
Good call, I will change that to `ExternalCall`, it is more clear.

Parameters: 
- _the service version should be optional. If it isn't provided, the latest version should be taken and the version should be then registered in the contract._
   - as discussed on Slack, we will not use version and id in the template because the service name will map to the serviceId + version. The user doesn't need to know this info, all one needs is the service name which will be unique.
- _argument keys don't need to be between ""_ 
   - sounds good
- _from is not needed_
   - I thought about adding the contractId as `from` to identify the source of the call, we can add it internally without exposing it to end user - just an idea to make it easier to track down the requests.

Properties:
- _result. The first result once the execution was successful. The type is a structure that is defined by the integrated service (ABI)_
   - So I just need to declare the type as `AbstractStructureType`?

- _status_ & _executionDate_
   - Ok

Agreed

**Comment by adridadou** [comment]
I think that the contractId should be passed automatically, no need to have it explicitly there IMO.

Regarding result, We will define a StructureType that will give us a DefinedStructureType (AbstractStructureType is the definition itself). So it will be the DefinedStructureType that we're going to use

**Comment by fforbeck** [comment]
Sounds good. Thanks!

**Comment by outkaj** [comment]
this can be closed, right?

**Comment by fforbeck** [comment]
Yes!
